# Generated by Django 3.1.dev20200208162335 on 2020-04-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
