# Generated by Django 3.1.dev20200208162335 on 2020-04-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='catslug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
