# Generated by Django 3.1.dev20200208162335 on 2020-04-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_catslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='catslug',
            field=models.SlugField(editable=False),
        ),
    ]
